# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: weekly
          timezone: Europe/Oslo
          time: '09:00'
      open-pull-requests-limit: 30
      labels:
          - '[Dependency] GitHub Action'
          - '[Type] Dependency'
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: weekly
          timezone: Europe/Oslo
          time: '09:00'
      open-pull-requests-limit: 30
      rebase-strategy: disabled
      labels:
          - '[Dependency] JavaScript'
          - '[Type] Dependency'
    - package-ecosystem: 'composer'
      directory: '/'
      schedule:
          interval: weekly
          timezone: Europe/Oslo
          time: '09:00'
      open-pull-requests-limit: 30
      labels:
          - '[Dependency] php'
          - '[Type] Dependency'
